### ISSUE TITLE
No buildable go source files

### ISSUE THREAD

**Issue by Mierdin** [vishvananda/netlink#17]
I'm having some issues installing this library. Still learning bits and pieces of the operations here, so feel free to point out a silly mistake.

It looks like I'm having problems retrieving building both the netlink and netns libraries. Any thoughts are appreciated. Output below:

```
~GOPATH/src/github.com $  go get github.com/vishvananda/netlink
vishvananda/netlink/netlink.go:14:2: no buildable Go source files in /Users/mierdin/Code/GO/src/github.com/vishvananda/netlink/nl

 ~GOPATH/src/github.com $  cd vishvananda/netlink
 ~GOPATH/src/github.com/vishvananda/netlink $  go build                                       
netlink.go:14:2: no buildable Go source files in /Users/mierdin/Code/GO/src/github.com/vishvananda/netlink/nl

 ~GOPATH/src/github.com/vishvananda/netlink $  go get github.com/vishvananda/netns
# github.com/vishvananda/netns
../netns/netns_unspecified.go:13: undefined: Namespace
../netns/netns_unspecified.go:17: undefined: Namespace
../netns/netns_unspecified.go:21: undefined: Namespace
../netns/netns_unspecified.go:25: undefined: Namespace
../netns/netns_unspecified.go:29: undefined: Namespace
../netns/netns_unspecified.go:33: undefined: Namespace

 ~GOPATH/src/github.com/vishvananda/netlink $  sudo -E go test github.com/vishvananda/netlink
netlink.go:14:2: no buildable Go source files in /Users/mierdin/Code/GO/src/github.com/vishvananda/netlink/nl
../netlink/netlink.go:14:2: no buildable Go source files in /Users/mierdin/Code/GO/src/github.com/vishvananda/netlink/nl
```

**Comment by Mierdin** [comment]
I managed to get this working on an Ubuntu 14.04 machine:

```
vagrant@client:~$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vagrant/Code/GO"
GORACE=""
GOROOT="/usr"
GOTOOLDIR="/usr/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"
```

The original problem machine was running OSX Yosemite:

```
 ~ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mierdin/Code/GO"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

Is there any hope in getting this running in Yosemite? I tinkered around with getting this working with gcc instead, but no joy on that either.

**Comment by dave-tucker** [comment]
@Mierdin No Linux. No Netlink :grinning:
If you want to work on this from OSX you have to use a VM, or alternatively use `boot2docker` and then
    
    docker run --privileged=true --rm -v "$(pwd)":/go/src/github.com/vishvananda/netlink -w /go/src/github.com/vishvananda/netlink golang:1.3 go test ./...

**Comment by vishvananda** [comment]
yes netlink and netns are only implemented for linux. Most of the netlink functionality should be possible to implement on osx, but it would require interfacing with the kernel control architechture: https://developer.apple.com/library/mac/documentation/Darwin/Conceptual/NKEConceptual/control/control.html#//apple_ref/doc/uid/TP40001858-CH227-DontLinkElementID_35

Unfortunately osx does not support network namespaces so those bits are not possible.

**Comment by Mierdin** [comment]
AH - thanks to both of you for this. My bad....like I said, new to this. Thanks for the tips!
